/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	jackistomv1 "k8s_customize_controller/pkg/apis/jackistom/v1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSylixoses implements SylixosInterface
type FakeSylixoses struct {
	Fake *FakeJackistomV1
	ns   string
}

var sylixosesResource = schema.GroupVersionResource{Group: "jackistom.k8s.io", Version: "v1", Resource: "sylixoses"}

var sylixosesKind = schema.GroupVersionKind{Group: "jackistom.k8s.io", Version: "v1", Kind: "Sylixos"}

// Get takes name of the sylixos, and returns the corresponding sylixos object, and an error if there is any.
func (c *FakeSylixoses) Get(ctx context.Context, name string, options v1.GetOptions) (result *jackistomv1.Sylixos, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sylixosesResource, c.ns, name), &jackistomv1.Sylixos{})

	if obj == nil {
		return nil, err
	}
	return obj.(*jackistomv1.Sylixos), err
}

// List takes label and field selectors, and returns the list of Sylixoses that match those selectors.
func (c *FakeSylixoses) List(ctx context.Context, opts v1.ListOptions) (result *jackistomv1.SylixosList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sylixosesResource, sylixosesKind, c.ns, opts), &jackistomv1.SylixosList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &jackistomv1.SylixosList{ListMeta: obj.(*jackistomv1.SylixosList).ListMeta}
	for _, item := range obj.(*jackistomv1.SylixosList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sylixoses.
func (c *FakeSylixoses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sylixosesResource, c.ns, opts))

}

// Create takes the representation of a sylixos and creates it.  Returns the server's representation of the sylixos, and an error, if there is any.
func (c *FakeSylixoses) Create(ctx context.Context, sylixos *jackistomv1.Sylixos, opts v1.CreateOptions) (result *jackistomv1.Sylixos, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sylixosesResource, c.ns, sylixos), &jackistomv1.Sylixos{})

	if obj == nil {
		return nil, err
	}
	return obj.(*jackistomv1.Sylixos), err
}

// Update takes the representation of a sylixos and updates it. Returns the server's representation of the sylixos, and an error, if there is any.
func (c *FakeSylixoses) Update(ctx context.Context, sylixos *jackistomv1.Sylixos, opts v1.UpdateOptions) (result *jackistomv1.Sylixos, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sylixosesResource, c.ns, sylixos), &jackistomv1.Sylixos{})

	if obj == nil {
		return nil, err
	}
	return obj.(*jackistomv1.Sylixos), err
}

// Delete takes name of the sylixos and deletes it. Returns an error if one occurs.
func (c *FakeSylixoses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sylixosesResource, c.ns, name), &jackistomv1.Sylixos{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSylixoses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sylixosesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &jackistomv1.SylixosList{})
	return err
}

// Patch applies the patch and returns the patched sylixos.
func (c *FakeSylixoses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *jackistomv1.Sylixos, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sylixosesResource, c.ns, name, pt, data, subresources...), &jackistomv1.Sylixos{})

	if obj == nil {
		return nil, err
	}
	return obj.(*jackistomv1.Sylixos), err
}
